import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRef } from 'react'

export default function Home() {
  const audioElement = useRef(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is a test of the audio tag
        </h1>
        <p>
          <audio playsInline autoPlay ref={audioElement}  />
        </p>
      </main>
    </div>
  )
}
